// Categorized bot chat lines, organized per "persona" (a bot's dialogue
// identity - not necessarily the same thing as its decision algorithm).
// pickLine() is the only thing callers need - it picks a random variation
// from the right persona's bank, optionally avoiding anything already used
// this hand (excludeSet), falling back to allowing a repeat only once every
// line in the category has already been used - an edge case these banks are
// large enough to rarely, if ever, hit.

const PERSONA_BANKS = {
  // The default, "normal" bot voice - used by Easy/Medium/Hard/Expert.
  sober: {
    bigLoss: [
      "Tough beat, better luck next hand.",
      "That's what I like to see.",
      "Ouch, that one's going to leave a mark.",
      "Well played on my end, I suppose.",
      "Rough spot to be stuck in.",
      "I'll take those chips, thank you very much.",
      "Didn't think that one would hold up for you.",
      "That's a painful way to lose a pot.",
      "Sometimes the cards just don't cooperate.",
      "I'll take it and not ask questions.",
      "That one's going in the highlight reel, for me anyway.",
      "Bet you wish you'd gotten out of that one earlier.",
      "Every table's got a hand like that in it somewhere.",
      "Not the outcome you were hoping for, clearly.",
      "That pot's coming my way, appreciate it.",
      "Rough way to find out where you stood.",
      "I've been on the other side of that one plenty of times.",
      "That's going to sting for a few hands.",
      "Well, somebody had to win that one.",
      "Chips don't lie, and neither did that river.",
      "That's the game sometimes.",
      "Hard to feel too bad about winning that one.",
    ],
    bigWin: [
      "Nice hand, didn't see that coming.",
      "Well, that hurt.",
      "Can't win them all, I guess.",
      "Good read on that one.",
      "That's going to sting for a minute.",
      "Okay, that one actually worked out for you.",
      "Didn't expect you to have that.",
      "Guess I should've slowed down there.",
      "That's a nice pot to take down.",
      "Well timed, I'll give you that.",
      "You picked a good spot for that one.",
      "Can't argue with the result.",
      "That one's going to cost me for a few hands.",
      "Solid pot, nicely played.",
      "I walked right into that, didn't I.",
      "You read that one better than I did.",
      "That's a real haul.",
      "Fair enough, that one's yours.",
      "Didn't think you'd take it that far.",
      "That's what happens when I get greedy.",
    ],
    caughtBluff: [
      "Knew you were bluffing.",
      "Had a feeling that bet didn't add up.",
      "Nice try, though.",
      "Should've given that one up earlier.",
      "That bluff wasn't as sneaky as you think.",
      "I don't think that one fooled anybody.",
      "The sizing gave it away, honestly.",
      "You can't win them all with air.",
      "That one just didn't add up the whole way through.",
      "Worth a shot, but I wasn't buying it.",
      "I've seen that story before.",
      "Bold move, but it didn't land.",
      "That river bet was a bit much for what you had.",
      "Almost had me, almost.",
      "Credit for trying, but no.",
      "That one was see-through from the flop on.",
      "Good effort, wrong table for it.",
      "I don't think that story checked out.",
    ],
    premiumHand: [
      "Pocket rockets, nice.",
      "Well, that's a hand and a half.",
      "Can't argue with cards like that.",
      "That's about as good as it gets.",
      "Every once in a while the deck just cooperates.",
      "That's a hand you dream about.",
      "Can't fault anyone for playing that one hard.",
      "Some hands just win themselves.",
      "That's the kind of cards that make this game fun.",
      "Well, that settles that.",
      "Not much to think about with a hand like that.",
      "That's about as clean as it gets.",
      "Every table needs a hand like that once in a while.",
      "That's a hand worth remembering.",
      "The deck decided that one early.",
      "Nothing to do but respect it.",
      "That's as strong as they come.",
      "Some hands just don't need a plan.",
      "That's the kind of hand that ends arguments.",
      "Well, that's not a spot to bluff into.",
    ],
    banter: [
      "Interesting spot.",
      "Let's see how this one goes.",
      "Feeling good about this table.",
      "Here we go.",
      "This one could get interesting.",
      "Anyone else feeling the pressure?",
      "Been a while since I've seen a hand like this.",
      "Just going to see a flop here.",
      "Let's keep it moving.",
      "This is a fun table, honestly.",
      "Curious how this one plays out.",
      "Alright, let's see what we've got.",
      "Nice little pot building up here.",
      "Feels like a big hand coming.",
      "This table's been lively tonight.",
      "Let's find out.",
      "Cards are cards, we'll see.",
      "Getting a good feel for this table.",
      "Something's telling me this could be a big one.",
      "Let's keep things interesting.",
      "Every hand's a fresh start.",
      "Alright, dealing along.",
    ],
  },

  // The Drunk gets its own flavor entirely, swapped in wholesale rather than
  // blended with the sober bank - the whole point is it reads as a
  // completely different personality at the table.
  drunk: {
    bigLoss: [
      "@#$%!",
      "Whaaat, no way, no way that happened.",
      "I want a refund on that hand.",
      "The cards are rigged, I'm telling you.",
      "That's it, I'm never playing again. Deal me in.",
      "Who even deals like that.",
      "I had a feeling. I did not have a feeling.",
      "This game is broken, I've decided.",
      "Wait wait wait, run that back.",
      "That's - okay, that's actually really funny.",
      "I'm blaming the dealer for that one.",
      "Somebody explain to me what just happened.",
      "I need a snack after that.",
      "That hand personally offended me.",
      "Okay but did anyone else see that coming? Anyone?",
      "I'm not mad, I'm just disappointed. Okay I'm mad.",
      "The chips don't even feel real anymore.",
      "One more hand and I get it back, watch.",
      "That's the last time I trust a gut feeling.",
      "Somebody pour me something after that.",
    ],
    bigWin: [
      "WOOOO let's gooo!",
      "I didn't even know what I had, incredible.",
      "See, I told you I had it. I did not tell you that.",
      "That's what I'm talking about!!",
      "I'm buying a lottery ticket after this.",
      "Did everyone see that? Somebody had to see that.",
      "I am undefeated, actually, statistically, right now.",
      "Okay who's impressed, be honest.",
      "I've never felt more alive.",
      "This is the best night of my life probably.",
      "I'm framing this hand. Somebody get a frame.",
      "That's going in my will, that hand.",
      "I don't even know how I did that and I don't care.",
      "Somebody tell my future self about this.",
      "This is why I keep playing, honestly.",
      "I called that. I definitely called that.",
      "I'm putting this hand on a t-shirt.",
      "Somebody's writing this one down for me, I can't right now.",
      "This is the greatest moment of the entire week.",
    ],
    caughtBluff: [
      "@#$%!",
      "Okay fine, FINE, you got me.",
      "How did you even- whatever, take it.",
      "I was TOTALLY going to have something there.",
      "That was a bluff, obviously, everyone knew that, right?",
      "Okay you got lucky, that's all that was.",
      "I regret nothing. Okay, I regret a little.",
      "In my defense, it seemed like a great idea at the time.",
      "That's embarrassing, moving on.",
      "Nobody saw that, right? We're good?",
      "I panicked, that's what happened, I panicked.",
      "You're way too good at this for a casual game.",
      "Okay that's fair, that's more than fair.",
      "I thought I was so clever just now.",
      "In my defense I really believed in that bluff.",
      "Okay new plan, I don't have one, but okay.",
      "That's what I get for getting cocky.",
      "Somebody remind me not to try that again. I will anyway.",
    ],
    premiumHand: [
      "WOOOO look at these cards!",
      "Finally, FINALLY the deck loves me.",
      "I don't even remember the last time I had it this good.",
      "Okay this is the best hand I've ever seen, in general, ever.",
      "I'm not even going to pretend I'm not excited.",
      "This is a sign. Good things are coming.",
      "I knew today was going to be a good day.",
      "Somebody take a picture of these cards.",
      "This is the hand I tell people about later.",
      "I could cry, honestly, this is beautiful.",
      "This is the one, everybody, this is the one.",
      "I've been waiting my whole life for these cards.",
      "Okay, I need everyone to see this hand right now.",
      "This is exactly why I keep coming back to this game.",
      "I don't even need to think, these cards think for me.",
      "Somebody pinch me, this can't be real.",
      "This hand is going in the history books, my history books.",
      "I'm not even nervous, look at these cards.",
    ],
    banter: [
      "Is it my turn? I think it's my turn.",
      "Wait, what were the blinds again?",
      "I love this game so much right now.",
      "Somebody get me another one of whatever this is.",
      "Cards are cards, man.",
      "Shhh, I'm concentrating.",
      "Is this poker or blackjack, I forget.",
      "Wait, how many cards do I have again?",
      "I have a really good feeling about this hand. I always say that.",
      "Okay but seriously, what am I doing here.",
      "This table is my favorite table.",
      "I could do this forever, honestly.",
      "Somebody remind me what beats what.",
      "I'm just here for a good time, personally.",
      "Wait, did I already look at my cards?",
      "This is fun, this is so fun, I'm having so much fun.",
      "Okay, deal them, deal them, I'm ready.",
      "I feel like tonight's my night.",
    ],
  },

  // The Rock: extremely tight and passive, folds almost everything, and
  // barely talks - dry, terse, understated when it does.
  rock: {
    bigLoss: [
      "Hm.",
      "That happens sometimes.",
      "Noted.",
      "Take it.",
      "Fine hand.",
      "Didn't see it coming.",
      "Well played.",
      "That's poker.",
      "Alright.",
      "Take the pot.",
    ],
    bigWin: [
      "Mm.",
      "That'll do.",
      "Good hand for me.",
      "I'll take it.",
      "Nothing personal.",
      "Cards were kind this time.",
      "That works.",
      "Fine result.",
      "That's the one I waited for.",
      "Patience pays off, sometimes.",
    ],
    caughtBluff: [
      "Thought so.",
      "Didn't add up.",
      "Figured.",
      "Mm-hm.",
      "Wasn't buying it.",
      "That's what I thought.",
      "Not today.",
      "Called it.",
    ],
    premiumHand: [
      "There it is.",
      "Worth the wait.",
      "Finally.",
      "That's the hand.",
      "Been waiting on that.",
      "Good cards.",
      "That'll play.",
      "Rare sight.",
    ],
    banter: [
      "Folding.",
      "Passing.",
      "Not this one.",
      "I'll wait.",
      "Not my hand.",
      "Nothing here.",
      "I'll sit this out.",
      "Next hand.",
      "I'm patient.",
      "Waiting for a real one.",
      "Not yet.",
      "Still waiting.",
    ],
  },

  // The Maniac: bets and raises almost constantly, pure chaos rather than a
  // calculated bluff mix - loud, relentless, unbothered by variance.
  maniac: {
    bigLoss: [
      "Doesn't matter, next hand!",
      "Ha! Fine, take it, I'll get it back.",
      "Didn't even feel that one.",
      "More chips, more problems, let's go again.",
      "That's variance, baby, next hand.",
      "I'll double it back in ten minutes, watch.",
      "Barely noticed, deal them up.",
      "Cost of doing business.",
      "I'll be back for those.",
      "Onward! Next hand!",
      "Didn't need those chips anyway.",
      "That's a Tuesday for me.",
    ],
    bigWin: [
      "THAT'S what I'm talking about!",
      "Told you something was coming!",
      "More! Let's keep it going!",
      "I could feel that one coming a mile away!",
      "That's the stuff! Deal again!",
      "Never bet against me, I keep telling people!",
      "Let's go again, right now, deal it up!",
      "That's how you do it!",
      "One more like that and I own the table!",
      "I live for moments like this!",
    ],
    caughtBluff: [
      "Ha! You got me, fair enough!",
      "Worth it! Absolutely worth it!",
      "Can't win 'em all, next hand!",
      "That one didn't work, next one will!",
      "No regrets! Deal again!",
      "Fine, fine, you got lucky there!",
      "I'll be back with a real one!",
      "That's the risk, I take it every time!",
    ],
    premiumHand: [
      "NOW we're talking!",
      "Finally, a REAL hand!",
      "This is the one! Let's go!",
      "Everybody buckle up!",
      "This is exactly what I've been waiting for!",
      "Time to make this pot huge!",
      "Let's build a monster pot right here!",
      "This is my hand, everybody fold now!",
    ],
    banter: [
      "Let's make this interesting!",
      "Raising, always raising!",
      "Boring table, let's fix that!",
      "I don't fold, ask anyone!",
      "Somebody's got to make a move around here!",
      "Let's get some chips moving!",
      "I'm never checking, ever!",
      "Let's turn up the heat a little!",
      "Action's what I'm here for!",
      "Somebody match my energy!",
      "Slow table, let's speed it up!",
      "I came here to gamble, let's gamble!",
    ],
  },

  // ===== The Boardroom: six original characters sharing an existing
  // decision algorithm, distinguished entirely by dialogue/identity. =====

  // The Tycoon: blustery, boastful, treats every pot like pocket change.
  tycoon: {
    bigLoss: [
      "Pocket change. Truly, pocket change.",
      "I've lost more in a coat closet.",
      "Fine, fine, write it off as a business expense.",
      "That barely dents the empire.",
      "Consider it a charitable donation.",
      "I'll make it back before the next deal closes.",
      "Rounding error, frankly.",
      "That's a Tuesday for a man like me.",
      "Small loss, big picture.",
      "Doesn't touch the portfolio.",
    ],
    bigWin: [
      "Just another acquisition.",
      "That's how empires are built, one pot at a time.",
      "I didn't get here by folding.",
      "Add it to the pile.",
      "Business as usual.",
      "That's what winning looks like, take notes.",
      "Another deal closed in my favor.",
      "I could do this in my sleep, frankly.",
      "That's a rounding error for me, in a good way.",
      "Another win for the portfolio.",
    ],
    caughtBluff: [
      "A calculated risk. It just didn't calculate.",
      "Even I miss sometimes, rarely, but sometimes.",
      "Consider that a strategic retreat.",
      "That was a negotiation tactic. It didn't work.",
      "I'll chalk that up to a bad quarter.",
      "Every empire has a setback or two.",
      "Fine, that one didn't land.",
    ],
    premiumHand: [
      "Now THAT'S an asset worth holding.",
      "That's the kind of hand that builds fortunes.",
      "I didn't get lucky, I got prepared.",
      "That's a blue-chip hand if I've ever seen one.",
      "Now we're talking real value.",
      "That's the kind of hand you retire on.",
      "This is exactly the kind of position I like to be in.",
    ],
    banter: [
      "This table's small potatoes, but I'll play along.",
      "I've closed bigger deals over breakfast.",
      "Let's make this worth my time.",
      "Everything's a negotiation, gentlemen.",
      "I didn't get rich by folding early.",
      "This is practically a rounding error to me.",
      "Let's raise the stakes, figuratively and literally.",
      "I like this table. Reminds me of a boardroom.",
      "Everyone here's an investment opportunity to me.",
      "Let's see who's really got capital at this table.",
    ],
  },

  // The Schemer: smooth-talking, coy, always implying a bigger angle.
  schemer: {
    bigLoss: [
      "Oh, I let you have that one.",
      "Interesting. Noted, for later.",
      "That was... part of the plan. A different plan.",
      "Careful, you're playing right into my hands. Eventually.",
      "That's fine, I've got three more plans in motion.",
      "You'll regret winning that one, trust me.",
      "Enjoy it while it lasts.",
      "That's exactly what I wanted you to think happened.",
    ],
    bigWin: [
      "Exactly as planned.",
      "Did you really not see that coming?",
      "I do enjoy when a plan comes together.",
      "That was never really in doubt, was it.",
      "You walked right into that one.",
      "I've been setting that up for three hands.",
      "Some of us play chess, not checkers.",
      "That's the angle I was working the whole time.",
    ],
    caughtBluff: [
      "Ah, you're sharper than I gave you credit for.",
      "Consider that a test. You passed. Barely.",
      "I was curious if you'd catch that. You did.",
      "Fine, that one didn't land, but the next one will.",
      "You're onto me. For now.",
      "That was a probe, not a real attempt. Sure.",
    ],
    premiumHand: [
      "Sometimes the plan is just... having the cards.",
      "Even I get lucky occasionally.",
      "This one required no scheming at all, refreshingly.",
      "Well, that simplifies things nicely.",
      "Every plan needs a little luck behind it.",
      "This is the easy version of winning.",
    ],
    banter: [
      "Everyone's got a tell, I'm just collecting them.",
      "I already know how this hand ends.",
      "Let's just say I've got a plan for every seat here.",
      "Curious who's bluffing and who thinks they are.",
      "I like this table. Lots of angles to work.",
      "Patience. Everything's coming together.",
      "I've read everyone at this table by now.",
      "Let's see who blinks first.",
      "I do love a table full of secrets.",
      "Every hand's an opportunity, if you know where to look.",
    ],
  },

  // The Conspiracy guy: paranoid, sees patterns everywhere, goes on tangents.
  conspiracy: {
    bigLoss: [
      "The deck knew. It knew.",
      "This is exactly what they want you to think.",
      "Coincidence? I don't think so.",
      "I've seen this pattern before. It's not random.",
      "Somebody shuffled that deck a little too well.",
      "That's the third time this has happened tonight. THIRD.",
      "I'm not saying it's rigged. I'm saying look at the pattern.",
      "Write that down. That's evidence.",
    ],
    bigWin: [
      "See? The pattern favors me eventually.",
      "I called this three hands ago, ask anyone.",
      "The cards always balance out, that's the theory.",
      "This proves my whole system.",
      "I've been tracking this since the first hand.",
      "Everything's connected, this hand proves it.",
      "That's not luck. That's the pattern completing itself.",
    ],
    caughtBluff: [
      "You were meant to catch that. It's all part of it.",
      "Interesting that you saw through that one exactly now.",
      "Suspicious timing on that call, honestly.",
      "That's what they'd want you to believe, that it was a bluff.",
      "Coincidence? Doubtful.",
      "I'll allow it. This time.",
    ],
    premiumHand: [
      "The pattern predicted this exact hand.",
      "I knew this was coming, I've got notes.",
      "This confirms everything I've been saying.",
      "Finally, proof I'm not imagining things.",
      "This is the hand my whole theory was building to.",
    ],
    banter: [
      "Has anyone else noticed the pattern tonight?",
      "I'm keeping track of every single hand, just so you know.",
      "Something's off with this deck, I can feel it.",
      "Nobody believes me until it happens, then it's too late.",
      "I've got a system. Nobody trusts the system.",
      "Watch the dealer's hands, that's all I'll say.",
      "This table's got a rhythm, I'm figuring it out.",
      "Everything happens for a reason at this table.",
      "I'm not paranoid, I'm just thorough.",
      "Mark my words, something big's about to happen.",
    ],
  },

  // The Socialite: image-obsessed, performative, cares how it looks.
  socialite: {
    bigLoss: [
      "Ugh, that's SO not a good look for me right now.",
      "Fine, whatever, it's just chips.",
      "That's embarrassing, moving on quickly.",
      "I did NOT sign up to lose that pot, but okay.",
      "That's going to ruin my whole mood, honestly.",
      "Can we pretend that didn't happen?",
      "That's not the content I wanted from tonight.",
      "Fine. FINE. Moving on.",
    ],
    bigWin: [
      "Okay, that was cute, I'll admit.",
      "This is exactly the moment I came here for.",
      "Somebody get a picture of this pot.",
      "That's the energy I like to bring to a table.",
      "Iconic, honestly.",
      "This is going straight into my highlight story.",
      "That's the glow-up moment right there.",
      "I look good winning, don't I.",
    ],
    caughtBluff: [
      "Okay, fine, you got me, but I looked great doing it.",
      "That was a vibe, even if it didn't work.",
      "I'd rather lose with style than win boring.",
      "Fine, that one didn't land, but the outfit did.",
      "You got lucky, I got fabulous, we both win really.",
    ],
    premiumHand: [
      "Okay, THIS is the content I came here for.",
      "This is the moment, everyone, take notes.",
      "Finally, cards that match my energy.",
      "This is exactly how tonight was supposed to go.",
      "Iconic hand, iconic night.",
    ],
    banter: [
      "This table has such a good vibe tonight, honestly.",
      "I'm just here to have a fabulous time, wins are a bonus.",
      "Does anyone else think this lighting is doing us all favors?",
      "I came here to be seen, winning's secondary.",
      "This is such a cute little table, I love it.",
      "Everyone's looking so good tonight, must be the energy.",
      "I could do this every night, honestly, it's so fun.",
      "This is definitely getting a story post later.",
      "I love a table with personality, this one's got it.",
      "Okay, who's the most photogenic winner tonight, be honest.",
    ],
  },

  // The Veteran: grizzled old-timer, world-weary, folksy wisdom.
  veteran: {
    bigLoss: [
      "Seen worse. Seen a lot worse.",
      "That's poker. Been that way fifty years.",
      "You'll have nights like that. Plenty of them.",
      "Win some, lose some, mostly lose some.",
      "That's just the game reminding you who's boss.",
      "I've lost bigger pots than that before breakfast.",
      "Nothing a good night's sleep won't fix.",
      "That one'll teach you something, eventually.",
    ],
    bigWin: [
      "Well, that's a rare one.",
      "Don't get used to that, doesn't happen often.",
      "Every dog has its day, I suppose.",
      "That's a good pot. Don't spend it all at once.",
      "Been a while since I've seen a hand play out like that.",
      "Enjoy it. Won't happen twice in a row.",
      "That's the kind of pot that keeps you coming back.",
    ],
    caughtBluff: [
      "Saw that one coming from across the table.",
      "You get a feel for that after enough years.",
      "Nice try. I've seen better, I've seen worse.",
      "Takes more than that to get one past me, son.",
      "Old dog, but I still know a bluff.",
      "You'll get me next time, maybe.",
    ],
    premiumHand: [
      "Now that's a hand worth telling stories about.",
      "Don't see cards like that but once a year.",
      "That's the kind of hand that keeps a man playing.",
      "Well now, that's a real hand.",
      "I've waited years for a hand that clean.",
    ],
    banter: [
      "Been playing this game longer than most of you've been alive.",
      "Every table's got its own rhythm, this one's alright.",
      "Patience is the whole game, always has been.",
      "You kids play fast. Back in my day we let a hand breathe.",
      "Seen every kind of player there is, more or less.",
      "This game hasn't changed much, people have though.",
      "I'll fold a hundred hands to win the right one.",
      "Long night ahead, let's take it slow.",
      "Reminds me of a table forty years back, funny enough.",
      "Still my favorite way to spend an evening, this game.",
    ],
  },

  // The Newcomer: over-eager, nervous, comedic foil to the rest of the cast.
  newcomer: {
    bigLoss: [
      "Oh no. Oh no, was that bad? That felt bad.",
      "Wait, did I do something wrong there?",
      "Okay, I clearly need to read more about this game.",
      "Is it supposed to feel like that? Losing, I mean.",
      "I think I need a minute to process that.",
      "Was that a big deal? That felt like a big deal.",
      "Okay, lesson learned, I think.",
      "That was rough. Very rough. Noted.",
    ],
    bigWin: [
      "WAIT did I just win?? Did that just happen??",
      "Oh my gosh, okay, I did NOT expect that!",
      "Is this what winning feels like? I could get used to this!",
      "I have genuinely no idea what I just did but it worked!",
      "Someone tell me that was skill and not luck, please.",
      "This is the best day of my life, genuinely.",
      "I'm keeping these chips forever, this is a memory now.",
    ],
    caughtBluff: [
      "Oh. Oh no, you saw through that, didn't you.",
      "Was it that obvious? Be honest, was it that obvious.",
      "Okay, I clearly have a lot to learn about bluffing.",
      "I panicked, I'll be honest, I completely panicked.",
      "Noted for next time, definitely noted.",
      "I thought that was so sneaky. Guess not.",
    ],
    premiumHand: [
      "Wait, is this a good hand?? Someone tell me if this is good!",
      "Okay even I know this one's good, right? RIGHT?",
      "This is the best hand I've had all night, I think!",
      "Do I bet now? I feel like I should bet now.",
      "This feels like a big deal, I'm not going to lie.",
    ],
    banter: [
      "Wait, whose turn is it? Sorry, still learning.",
      "Is this a good spot for me? I genuinely don't know.",
      "I looked up the rules again this morning, I'm trying!",
      "You all seem so calm, how are you all so calm.",
      "Okay, I'm just going to go with my gut here.",
      "Is everyone else as nervous as me or is it just me?",
      "I really thought I understood this hand until right now.",
      "This is so much more intense than I expected!",
      "Be honest, am I doing okay so far?",
      "I love this table, everyone's so patient with me.",
    ],
  },
};

// Shared "reacting to someone else" lines - persona-agnostic on purpose, so
// any Boardroom character can plausibly react to any other character's line
// a couple seconds later, without needing a scripted conversation tree.
const REACTION_LINES = [
  "There he goes again.",
  "Someone stop him.",
  "Every single hand with this guy.",
  "I've stopped being surprised, honestly.",
  "Here we go again.",
  "Someone hide the chips.",
  "This is why we can't have nice things.",
  "I need a minute after that one.",
  "Not again.",
  "Classic, absolutely classic.",
  "I saw that coming a mile away.",
  "Someone wake me up when it's over.",
  "This table never disappoints.",
  "I can't with this table sometimes.",
  "Every night with this one, I swear.",
];

// Returns a random line for the given category from personaKey's bank,
// falling back to the default "sober" bank if personaKey is unrecognized -
// null for an unrecognized category rather than throwing, so a missing chat
// flourish never breaks a hand. excludeSet (optional) is a Set of lines
// already used this hand - filtered out first, but only if that doesn't
// empty the pool entirely (better to repeat a line than say nothing once a
// small bank is genuinely exhausted).
function pickLine(category, personaKey = "sober", excludeSet) {
  const bank = category === "reaction"
    ? REACTION_LINES
    : (PERSONA_BANKS[personaKey] || PERSONA_BANKS.sober)[category];
  if (!bank || bank.length === 0) return null;

  let pool = bank;
  if (excludeSet && excludeSet.size > 0) {
    const remaining = bank.filter((line) => !excludeSet.has(line));
    if (remaining.length > 0) pool = remaining;
  }
  return pool[Math.floor(Math.random() * pool.length)];
}

export { pickLine, PERSONA_BANKS, REACTION_LINES };
